apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ledger
spec:
  project: ledger
  source:
    repoURL: https://github.com/unifist/platform
    path: unums/{{ unum }}/apps/ledger
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ledger
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
