apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: ledger
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: http
    interval: 15s
    honorLabels: true
