apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../api/kubernetes/base/
- ../../gui/kubernetes/base/
- ../../daemon/kubernetes/base/
- ../../cron/kubernetes/base/
- ../../redis/kubernetes/base/
