apiVersion: apps/v1
kind: Deployment
metadata:
  name: daemon
  namespace: ledger
spec:
  template:
    spec:
      containers:
      - name: daemon
        image: unum-apps-ledger-daemon
        imagePullPolicy: Never
        command: ["python", "-m", "ptvsd", "--host", "0.0.0.0", "--port", "5678", "/opt/service/bin/daemon.py"]
        env:
        - name: LOG_LEVEL
          value: INFO
        ports:
        - name: debug
          containerPort: 5678
          protocol: TCP
