apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ledger
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
      - name: migrate
        image: unum-apps-ledger-api
        command: ["/opt/service/bin/migrate.py"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: INFO
        volumeMounts:
        - name: secret
          mountPath: "/opt/service/secret"
          readOnly: true
      containers:
      - name: api
        image: unum-apps-ledger-api
        imagePullPolicy: Always
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: WARNING
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /health
            port: 80
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /health
            port: 80
        volumeMounts:
        - name: secret
          mountPath: "/opt/service/secret"
          readOnly: true
      volumes:
      - name: secret
        secret:
          secretName: secret
---
kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: ledger
  labels:
    app: api
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
